import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from '@/shared/components/Nav'
// map components
import { MapView } from '@/app/(map)/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* map*/}
        <h1 className="text-3xl font-bold underline fixed z-30 mx-[50px] my-4">ChivoMap</h1>
        <MapView />

        {children}

        {/* nav component */}
        <div className="fixed bottom-2 w-full flex items-center justify-center nav-component">
          <Nav />
        </div>
      </body>
    </html>
  )
}
